language: generic
sudo: required

services:
  - docker

notifications:
  on_success: never
  on_failure: always

before_install:
  - sudo apt-get -y install curl

script:
  - docker build -t pe46dro/xbackbone-docker ./src/
  - mkdir -p ./xbb/storage
  - mkdir -p ./xbb/database
  - mkdir -p ./xbb/logs
  - sudo chown -R 1000:1000 ./xbb
  - pwd
  - docker run -p 80:80 -d -v /home/travis/build/Pe46dro/XBackBone-docker/xbb/storage:/app/storage -v /home/travis/build/Pe46dro/XBackBone-docker/xbb/database:/app/resources/database -v /home/travis/build/Pe46dro/XBackBone-docker/xbb/logs:/app/logs -e PHP_UPLOAD_MAX_FILESIZE=1G -e URL=http:\/\/127.0.0.1 --name xbackbone pe46dro/xbackbone-docker
  - sleep 15 && curl --silent --show-error --fail http://127.0.0.1/login
  # Test fix #3
  - docker stop xbackbone 
  - docker start xbackbone
  - sleep 15 && curl --silent --show-error --fail http://127.0.0.1/login
  - "curl  --silent --show-error --fail 'http://127.0.0.1/login' -H 'upgrade-insecure-requests: 1' -H 'content-type: application/x-www-form-urlencoded' --data 'username=admin&password=admin' --compressed --cookie-jar cookie.txt -SD -"
  - "curl  --silent --show-error --fail 'http://127.0.0.1/user/1/refreshToken' -X POST --compressed -b cookie.txt -SD -"
  - "curl  --silent --show-error --fail 'http://127.0.0.1/user/1/config/script'  -O -J --location-trusted --max-redirs 10 --output script.sh --compressed -b cookie.txt -SD -"
  - ls -la
  - dd if=/dev/zero of=file.txt count=512 bs=1048576
  - bash xbackbone_uploader_admin.sh file.txt
  - docker rm xbackbone
  - docker volume create xbb_storage
  - docker volume create xbb_database
  - docker volume create xbb_logs
  - docker run -p 80:80 -d -v xbb_storage:/app/storage -v xbb_database:/app/resources/database -v xbb_logs:/app/logs -e PHP_UPLOAD_MAX_FILESIZE=1G -e URL=http:\/\/127.0.0.1 --name xbackbone pe46dro/xbackbone-docker
  - sleep 15 && curl --silent --show-error --fail http://127.0.0.1/login
  - "curl  --silent --show-error --fail 'http://127.0.0.1/login' -H 'upgrade-insecure-requests: 1' -H 'content-type: application/x-www-form-urlencoded' --data 'username=admin&password=admin' --compressed --cookie-jar cookie.txt -SD -"
  - "curl  --silent --show-error --fail 'http://127.0.0.1/user/1/refreshToken' -X POST --compressed -b cookie.txt -SD -"
  - "curl  --silent --show-error --fail 'http://127.0.0.1/user/1/config/script'  -O -J --location-trusted --max-redirs 10 --output script.sh --compressed -b cookie.txt -SD -"
  - ls -la
  - dd if=/dev/zero of=file.txt count=512 bs=1048576
  - bash xbackbone_uploader_admin.sh file.txt
