language: generic
sudo: required

services:
  - docker

notifications:
  on_success: never
  on_failure: always

before_install:
  - sudo apt-get -y install curl

script:
  # Test docker image
  - docker build -t pe46dro/xbackbone-docker ./src/
  
  - mkdir -p ./xbb/storage
  - mkdir -p ./xbb/database
  - mkdir -p ./xbb/logs
  - mkdir -p ./xbb/config
  - sudo chown -R 1002:1002 ./xbb

  - docker run -p 80:80 -d -v $(pwd)/xbb/storage:/app/storage -v $(pwd)/xbb/database:/app/resources/database -v $(pwd)/xbb/logs:/app/logs -v $(pwd)/xbb/config:/app/config -e PHP_UPLOAD_MAX_FILESIZE=1G -e CONTAINER_UID=1002 -e URL=http:\/\/127.0.0.1 --name xbackbone pe46dro/xbackbone-docker
  - bash tests/test_login.sh
  
  # Test fix #3
  - docker stop xbackbone 
  - docker start xbackbone
  - docker logs xbackbone
  
  # Test login and upload
  - bash tests/test_login.sh
  - bash tests/test_upload.sh
  - bash tests/clear.sh
  
  # Test volumes
  - docker volume create xbb_storage
  - docker volume create xbb_database
  - docker volume create xbb_logs
  - docker volume create xbb_config
  - docker run -p 80:80 -d -v xbb_storage:/app/storage -v xbb_database:/app/resources/database -v xbb_logs:/app/logs -v xbb_config:/app/config -e PHP_UPLOAD_MAX_FILESIZE=1G  -e CONTAINER_UID=1002 -e URL=http:\/\/127.0.0.1 --name xbackbone pe46dro/xbackbone-docker
  - bash tests/test_login.sh
  
  # Test fix #3
  - docker stop xbackbone 
  - docker start xbackbone
  
  # Test login and upload
  - bash tests/test_login.sh
  - bash tests/test_upload.sh
  - bash tests/clear.sh
  
  # Test MySQL
  - docker-compose up -d
  - docker-compose ps
  - bash tests/test_login.sh
  
  # Test fix #3
  - docker-compose stop
  - docker-compose start
  - docker-compose logs
  
  # Test login and upload
  - bash tests/test_login.sh
  - bash tests/test_upload.sh
  - bash tests/clear.sh
