version: '3.3'
services:
  app:
    build: ./src
    restart: always
    ports:
      - '8083:80'
    expose:
      - '8083'
    networks:
      - default
      - frontend
      - backend
    environment:
      - APP_NAME=${APP_NAME}
      - URL=${URL}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE}
      - DB_TYPE=${DB_TYPE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - "db"
    volumes:
      - xbb_storage:/app/storage
      - xbb_database:/app/resources/database
      - xbb_logs:/app/logs
      - xbb_config:/app/config
  db:
    image: mariadb:10.4
    restart: always
    volumes:
      - xbb_mariadb:/var/lib/mysql
    networks:
      - backend
    environment:
      - APP_NAME=${APP_NAME}
      - URL=${URL}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE}
      - DB_TYPE=${DB_TYPE}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
  frontend:
  backend:
  default:
    external: true
    name: nginx-network

volumes:
  xbb_mariadb:
  xbb_storage:
  xbb_database:
  xbb_logs:
  xbb_config:
